# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-17 22:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_experiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='Isotopic_labeling',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='specimen_sg',
            name='Sequence_Database_Public_Availability',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
