# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-18 15:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20180317_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='Nb_samples',
            field=models.IntegerField(default=0),
        ),
    ]
