# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 12:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_auto_20180318_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen_apms',
            name='Sequence_Database_Public_Availability',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='specimen_gb',
            name='Sequence_Database_Public_Availability',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='specimen_ptm',
            name='Sequence_Database_Public_Availability',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
