# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-20 22:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_auto_20180319_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='Factor_name_lst',
            new_name='Conditions_lst',
        ),
        migrations.AddField(
            model_name='experiment',
            name='Nb_conditions',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='Nb_factors',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='specimen_apms',
            name='CUnit',
            field=models.CharField(choices=[('nmol/ul', 'ng/\u03bcl'), ('umol/ul', '\u03bcg/\u03bcl'), ('mmol/ul', 'mg/\u03bcl')], max_length=10),
        ),
        migrations.AlterField(
            model_name='specimen_gb',
            name='CUnit',
            field=models.CharField(choices=[(True, '\u03bcl'), (False, 'ml')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='specimen_ptm',
            name='CUnit',
            field=models.CharField(choices=[('nmol/ul', 'ng/\u03bcl'), ('umol/ul', '\u03bcg/\u03bcl'), ('mmol/ul', 'mg/\u03bcl')], max_length=10),
        ),
        migrations.AlterField(
            model_name='specimen_sg',
            name='CUnit',
            field=models.CharField(choices=[('nmol/ul', 'ng/\u03bcl'), ('umol/ul', '\u03bcg/\u03bcl'), ('mmol/ul', 'mg/\u03bcl')], max_length=10),
        ),
        migrations.AlterField(
            model_name='specimen_sg',
            name='Protein_Concentration',
            field=models.FloatField(default='nmol/ul'),
        ),
        migrations.AlterField(
            model_name='specimen_sg',
            name='Volume',
            field=models.FloatField(default=True),
        ),
    ]
