# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-20 23:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_auto_20180320_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='Conditions_lst',
            new_name='Conditions_list',
        ),
        migrations.AddField(
            model_name='experiment',
            name='Factor_name_lst',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='specimen_sg',
            name='Protein_Concentration',
            field=models.FloatField(default='\u03bcg/\u03bcl'),
        ),
        migrations.AlterField(
            model_name='specimen_sg',
            name='Sample_Type',
            field=models.CharField(choices=[('cell_pellet', 'cell pellet'), ('tissue', 'tissue'), ('protein_extract', 'protein extract')], default='cell pellet', max_length=50),
        ),
        migrations.AlterField(
            model_name='specimen_sg',
            name='Volume',
            field=models.FloatField(default='\u03bcl'),
        ),
    ]
