# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 12:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_auto_20180321_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='Project_summary',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='specimen_sg',
            name='CUnit',
            field=models.CharField(choices=[('nmol/ul', 'ng/\u03bcl'), ('umol/ul', '\u03bcg/\u03bcl'), ('mmol/ul', 'mg/\u03bcl')], default='\u03bcg/\u03bcl', max_length=10),
        ),
        migrations.AlterField(
            model_name='specimen_sg',
            name='Protein_Concentration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='specimen_sg',
            name='VUnit',
            field=models.BooleanField(choices=[(True, '\u03bcl'), (False, 'ml')], default='\u03bcl'),
        ),
        migrations.AlterField(
            model_name='specimen_sg',
            name='Volume',
            field=models.FloatField(),
        ),
    ]
