# Generated by Django 2.1.4 on 2018-12-13 14:30

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_auto_20180410_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen_apms',
            name='Sequence_Database_File',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='specimen_gb',
            name='Gel_GelBand_Image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='specimen_gb',
            name='Sequence_Database_File',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='specimen_ptm',
            name='Sequence_Database_File',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='specimen_sg',
            name='Sequence_Database_File',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/pportal/dev2Sep18/myenv3/pportal3/media'), upload_to=''),
        ),
    ]
