# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-14 19:47
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_auto_20181213_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen_sg',
            name='Sequence_Database_File',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/pportal/dev2Sep18/myenv3/pportal4/media'), upload_to=''),
        ),
    ]
