# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_auto_20190114_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='Affiliation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Analysis_Type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Study_Type',
        ),
        migrations.AddField(
            model_name='analysis',
            name='Analysis_Type',
            field=models.CharField(choices=[('shotgun', 'Shotgun analysis'), ('APMS', 'Affinity-Purification MS (AP-MS)'), ('PTMs', 'PTM analysis'), ('gelband', 'Protein gel band analysis'), ('proteinmass', 'Protein mass determination'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='Study_Type',
            field=models.CharField(choices=[('VIB', 'VIB'), ('Academic', 'Academic'), ('Non-Academic', 'Non Academic')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Affiliation',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Email',
            field=models.EmailField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Main_Analysis_Type',
            field=models.CharField(choices=[('shotgun', 'Shotgun analysis'), ('APMS', 'Affinity-Purification MS (AP-MS)'), ('PTMs', 'PTM analysis'), ('gelband', 'Protein gel band analysis'), ('proteinmass', 'Protein mass determination'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Group_Leader',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Issue',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
