# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-20 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_auto_20190120_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='Study_Type',
        ),
        migrations.AddField(
            model_name='profile',
            name='Affiliation_Type',
            field=models.CharField(choices=[('VIB', 'VIB'), ('Academic', 'Academic'), ('Non-Academic', 'Non Academic')], max_length=50, null=True),
        ),
    ]
