# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-20 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0012_auto_20190120_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Issue',
            new_name='Project_ID',
        ),
    ]
