# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-04 14:28
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0013_auto_20190120_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen_sg',
            name='Protein_Concentration',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='specimen_sg',
            name='Sequence_Database_File',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home/pportal/dev2Sep18/myenv3/pportal3/media'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='specimen_sg',
            name='Volume',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
